import type { Localized } from "@/lib/i18n";

export type Category = "industrial" | "commercial" | "residential" | "villas" | "leisure" | "poultry";

/** "ivbc" = delivered by Ideal Venture (2022+). "legacy" = Venture General Contracting LLC (2005+). */
export type Era = "ivbc" | "legacy";

export type Project = {
  slug: string;
  title: Localized;
  category: Category;
  era: Era;
  location: Localized;
  /** Built-up area in square feet, when documented. */
  areaSqft?: number;
  client?: string; // corporate clients only — private individuals are never named
  consultant?: string;
  completed?: boolean;
  images: string[];
  featured?: boolean;
};

export const categories: { id: Category; label: Localized }[] = [
  { id: "industrial", label: { en: "Industrial & Warehouses", ar: "صناعي ومستودعات" } },
  { id: "commercial", label: { en: "Commercial & Accommodation", ar: "تجاري وسكن عمال" } },
  { id: "residential", label: { en: "Residential Buildings", ar: "مبانٍ سكنية" } },
  { id: "villas", label: { en: "Villas", ar: "فلل" } },
  { id: "leisure", label: { en: "Tourism & Leisure", ar: "سياحة وترفيه" } },
  { id: "poultry", label: { en: "Poultry Farms", ar: "مزارع دواجن" } },
];

const img = (name: string) => `/images/projects/${name}.webp`;

const L = {
  dubai: { en: "Dubai", ar: "دبي" },
  dic: { en: "Dubai Industrial City", ar: "مدينة دبي الصناعية" },
  jafza: { en: "JAFZA, Dubai", ar: "جافزا، دبي" },
  hfza: { en: "Hamriyah Free Zone, Sharjah", ar: "المنطقة الحرة بالحمرية، الشارقة" },
  dip: { en: "Dubai Investments Park", ar: "مجمع دبي للاستثمار" },
  alWarqa: { en: "Al Warqa, Dubai", ar: "الورقاء، دبي" },
} satisfies Record<string, Localized>;

export const projects: Project[] = [
  // ───────────── Ideal Venture (2022 onwards) ─────────────
  {
    slug: "contemporary-g1-villa",
    title: { en: "Contemporary G+1 Private Villa", ar: "فيلا خاصة عصرية (أرضي + أول)" },
    category: "villas",
    era: "ivbc",
    location: L.dubai,
    images: [img("ivbc-g1-villa")],
    featured: true,
  },
  {
    slug: "warehouse-office-labour-accommodation",
    title: {
      en: "G+1 Warehouse, Office & Labour Accommodation with Yard Levelling",
      ar: "مستودع ومكاتب (أرضي + أول) وسكن عمال مع تسوية الساحة",
    },
    category: "industrial",
    era: "ivbc",
    location: { en: "UAE", ar: "الإمارات" },
    images: [],
  },
  {
    slug: "villa-maintenance",
    title: {
      en: "Villa Maintenance — Villa, Kitchen Block, Service Block & Compound Wall (2 villas)",
      ar: "صيانة فلل — الفيلا والمطبخ والملحق الخدمي وسور المجمع (فيلتان)",
    },
    category: "villas",
    era: "ivbc",
    location: L.dubai,
    images: [],
  },

  // ───────────── Legacy: Venture General Contracting LLC ─────────────
  {
    slug: "mubarak-sons-dic",
    title: { en: "Warehouse, Workshop & Office (G+M)", ar: "مستودع وورشة ومكاتب (أرضي + ميزانين)" },
    category: "industrial",
    era: "legacy",
    location: L.dic,
    areaSqft: 120_017.69,
    client: "Mubarak & Sons General Transport",
    consultant: "Chawla Architectural & Consulting Engineers",
    completed: true,
    images: [img("mubarak-sons-dic"), img("mubarak-sons-dic-render"), img("mubarak-sons-dic-aerial")],
    featured: true,
  },
  {
    slug: "star-steel-hamriyah",
    title: { en: "Rebar, Structural and Cut & Bend Factory", ar: "مصنع حديد التسليح والهياكل والقص والثني" },
    category: "industrial",
    era: "legacy",
    location: L.hfza,
    areaSqft: 335_200,
    client: "Star Steel",
    consultant: "Al Jassim Engineering Consultants",
    completed: true,
    images: [img("star-steel-hamriyah"), img("star-steel-interior")],
    featured: true,
  },
  {
    slug: "hamriyah-pipe-painting-blasting-sheds",
    title: {
      en: "Pipe Shed, Painting Shed, RT Bunker & Blasting Shed",
      ar: "حظائر الأنابيب والطلاء والسفع الرملي ومخبأ الفحص الإشعاعي",
    },
    category: "industrial",
    era: "legacy",
    location: L.hfza,
    areaSqft: 148_014.6,
    consultant: "Capital Engineering Consultants",
    images: [img("lamprell-hamriyah"), img("lamprell-hamriyah-2")],
    featured: true,
  },
  {
    slug: "caterpillar-training-center",
    title: { en: "Caterpillar Training Centre", ar: "مركز تدريب كاتربيلر" },
    category: "industrial",
    era: "legacy",
    location: L.jafza,
    client: "Al Tayer Stocks LLC",
    consultant: "Orion Engineering Consultants",
    completed: true,
    images: [img("caterpillar-jafza")],
    featured: true,
  },
  {
    slug: "technopark-office-warehouse",
    title: { en: "G+M Office & Warehouse", ar: "مكاتب ومستودع (أرضي + ميزانين)" },
    category: "industrial",
    era: "legacy",
    location: { en: "Technopark, Dubai", ar: "تكنوبارك، دبي" },
    areaSqft: 63_064.36,
    client: "Acme Middle East FZCO",
    consultant: "Corporate Planners Engineering Consultants",
    completed: true,
    images: [img("acme-technopark"), img("acme-technopark-2")],
  },
  {
    slug: "liftek-hamriyah",
    title: { en: "Office, Warehouse & Service Block", ar: "مكاتب ومستودع وملحق خدمي" },
    category: "industrial",
    era: "legacy",
    location: L.hfza,
    areaSqft: 41_200,
    client: "Liftek FZC",
    consultant: "Corporate Planners Engineering Consultants",
    completed: true,
    images: [img("liftek-hamriyah"), img("liftek-render"), img("liftek-warehouse")],
    featured: true,
  },
  {
    slug: "albwardy-dmc",
    title: { en: "G+1 Office, Workshop & Service Blocks", ar: "مكاتب وورشة وملاحق خدمية (أرضي + أول)" },
    category: "industrial",
    era: "legacy",
    location: { en: "Dubai Maritime City", ar: "مدينة دبي الملاحية" },
    areaSqft: 42_147,
    client: "Albwardy Marine Engineering",
    consultant: "Isometric Engineering Consultancy",
    images: [img("albwardy-dmc")],
  },
  {
    slug: "gbmt-dic",
    title: {
      en: "Design & Build — G+M Office, Workshop & Utility Buildings",
      ar: "تصميم وتنفيذ — مكاتب وورشة ومبانٍ خدمية (أرضي + ميزانين)",
    },
    category: "industrial",
    era: "legacy",
    location: L.dic,
    areaSqft: 64_600,
    client: "GBMT Structural Steel Manufacturing",
    consultant: "Corporate Planners Engineering Consultants",
    images: [img("gbmt-dic")],
  },
  {
    slug: "age-group-ras-al-khor",
    title: { en: "Office Buildings & Warehouse", ar: "مبانٍ مكتبية ومستودع" },
    category: "industrial",
    era: "legacy",
    location: { en: "Ras Al Khor, Dubai", ar: "رأس الخور، دبي" },
    client: "AGE Group",
    consultant: "Al Jassim Engineering Consultants",
    completed: true,
    images: [img("age-steel"), img("age-intrade"), img("age-warehouse")],
  },
  {
    slug: "global-heavy-equipment",
    title: { en: "Office + Facility", ar: "مكاتب ومرفق تشغيلي" },
    category: "industrial",
    era: "legacy",
    location: L.jafza,
    areaSqft: 21_326.8,
    client: "Global Heavy Equipment",
    consultant: "Al Jassim Engineering Consultants",
    completed: true,
    images: [img("global-heavy-equipment")],
  },
  {
    slug: "universal-machinery",
    title: { en: "Office Building", ar: "مبنى مكاتب" },
    category: "industrial",
    era: "legacy",
    location: L.jafza,
    client: "Universal Machinery",
    completed: true,
    images: [img("universal-machinery")],
  },
  {
    slug: "alpine-metals",
    title: { en: "Office + Facility", ar: "مكاتب ومرفق تشغيلي" },
    category: "industrial",
    era: "legacy",
    location: L.jafza,
    areaSqft: 13_476,
    client: "Alpine Metals",
    consultant: "Bhatia Brothers Consultants",
    completed: true,
    images: [img("alpine-metals-jafza")],
  },
  {
    slug: "sunree-dip",
    title: { en: "Office, Warehouse & Service Block", ar: "مكاتب ومستودع وملحق خدمي" },
    category: "industrial",
    era: "legacy",
    location: L.dip,
    client: "Sunree Industries",
    completed: true,
    images: [img("sunree-dip"), img("sunree-dip-2")],
  },
  {
    slug: "al-jazeera-marine",
    title: { en: "Office, Warehouse & Service Block", ar: "مكاتب ومستودع وملحق خدمي" },
    category: "industrial",
    era: "legacy",
    location: L.hfza,
    client: "Al Jazeera Marine Services",
    completed: true,
    images: [img("al-jazeera-marine")],
  },
  {
    slug: "acme-building-materials",
    title: { en: "Office, Warehouse & Service Block", ar: "مكاتب ومستودع وملحق خدمي" },
    category: "industrial",
    era: "legacy",
    location: { en: "Ras Al Khor, Dubai", ar: "رأس الخور، دبي" },
    client: "Acme Building Materials",
    completed: true,
    images: [img("office-showroom")],
  },
  {
    slug: "loops-automation-dic",
    title: { en: "G+M Office, Warehouse & Workshop", ar: "مكاتب ومستودع وورشة (أرضي + ميزانين)" },
    category: "industrial",
    era: "legacy",
    location: L.dic,
    areaSqft: 45_046.36,
    client: "Loops Automation",
    consultant: "Winner Holistic Consultants",
    images: [],
  },
  {
    slug: "jafza-south-open-shed",
    title: {
      en: "Open Shed, G+M Building & Additional Facilities",
      ar: "حظيرة مفتوحة ومبنى (أرضي + ميزانين) ومرافق إضافية",
    },
    category: "industrial",
    era: "legacy",
    location: { en: "JAFZA South, Dubai", ar: "جافزا الجنوبية، دبي" },
    areaSqft: 55_580,
    consultant: "Al Jassim Engineering Consultants",
    images: [],
  },
  {
    slug: "lamprell-pit-foundation",
    title: {
      en: "Pit Foundation for Plate Bending Machine & Site Levelling",
      ar: "أساسات حفرة لآلة ثني الألواح وتسوية الموقع",
    },
    category: "industrial",
    era: "legacy",
    location: L.hfza,
    client: "Lamprell Energy Ltd",
    consultant: "Al Shams Al Sathaa Engineering Consultants",
    completed: true,
    images: [],
  },
  {
    slug: "ferrofab-dip",
    title: { en: "Office, Warehouse & Factory Shed", ar: "مكاتب ومستودع وحظيرة مصنع" },
    category: "industrial",
    era: "legacy",
    location: L.dip,
    client: "Ferrofab FZE",
    completed: true,
    images: [],
  },
  {
    slug: "labour-camp-jebel-ali",
    title: { en: "G+3 Labour Camp", ar: "سكن عمال (أرضي + 3 طوابق)" },
    category: "commercial",
    era: "legacy",
    location: { en: "Jebel Ali Industrial, Dubai", ar: "جبل علي الصناعية، دبي" },
    areaSqft: 99_465.3,
    client: "Cleveland Bridge Engineering Middle East",
    consultant: "Global Engineering Office (GEO)",
    images: [img("labour-camp-jebel-ali"), img("labour-camp-jebel-ali-2")],
    featured: true,
  },
  {
    slug: "uaq-shed-labour-accommodation",
    title: { en: "G+M Labour Accommodation & Shed", ar: "سكن عمال وحظيرة (أرضي + ميزانين)" },
    category: "commercial",
    era: "legacy",
    location: { en: "Umm Al Thoub, Umm Al Quwain", ar: "أم الثعوب، أم القيوين" },
    areaSqft: 12_814.08,
    client: "Heat Shield Air Conditioning",
    consultant: "ENJAZ Engineering Consultants",
    images: [img("uaq-shed-labour")],
  },
  {
    slug: "labour-accommodation-dubai",
    title: { en: "Labour Accommodation Buildings", ar: "مبانٍ لسكن العمال" },
    category: "commercial",
    era: "legacy",
    location: L.dubai,
    completed: true,
    images: [img("labour-accommodation"), img("labour-accommodation-2")],
  },
  {
    slug: "latifa-hospital-nicu",
    title: { en: "Latifa Hospital NICU (G+1)", ar: "وحدة العناية المركزة لحديثي الولادة — مستشفى لطيفة" },
    category: "commercial",
    era: "legacy",
    location: L.dubai,
    client: "Al Tayer Stocks LLC",
    images: [],
  },
  {
    slug: "g5-building-al-warqa",
    title: { en: "G+5 Residential & Commercial Building", ar: "مبنى سكني وتجاري (أرضي + 5 طوابق)" },
    category: "residential",
    era: "legacy",
    location: L.alWarqa,
    areaSqft: 62_846.21,
    consultant: "Align Engineering Consultants",
    images: [img("g5-building-al-warqa")],
    featured: true,
  },
  {
    slug: "g6-building-al-warqa",
    title: { en: "G+6 Residential & Commercial Building", ar: "مبنى سكني وتجاري (أرضي + 6 طوابق)" },
    category: "residential",
    era: "legacy",
    location: L.alWarqa,
    consultant: "Align Engineering Consultants",
    images: [img("g6-building-al-warqa")],
  },
  {
    slug: "g2-residential-hor-al-anz",
    title: { en: "G+2 Residential Building & Parking", ar: "مبنى سكني (أرضي + 2) مع مواقف" },
    category: "residential",
    era: "legacy",
    location: { en: "Hor Al Anz, Dubai", ar: "هور العنز، دبي" },
    consultant: "Western Engineering Consultants",
    completed: true,
    images: [],
  },
  {
    slug: "villa-jumeirah-golf-estates",
    title: { en: "B+G+1 Private Villa", ar: "فيلا خاصة (قبو + أرضي + أول)" },
    category: "villas",
    era: "legacy",
    location: { en: "Jumeirah Golf Estates, Dubai", ar: "جميرا جولف إستيتس، دبي" },
    areaSqft: 9_372.57,
    consultant: "Architectural Corner",
    completed: true,
    images: [img("villa-jumeirah-golf-estates")],
    featured: true,
  },
  {
    slug: "villa-jumeirah-first",
    title: { en: "B+G+1 Private Villa", ar: "فيلا خاصة (قبو + أرضي + أول)" },
    category: "villas",
    era: "legacy",
    location: { en: "Jumeirah 1, Dubai", ar: "جميرا 1، دبي" },
    areaSqft: 14_199.9,
    consultant: "Emsquare Engineering Consultants",
    images: [img("villa-jumeirah-first")],
  },
  {
    slug: "villa-al-khawaneej",
    title: { en: "G+1 Private Villa", ar: "فيلا خاصة (أرضي + أول)" },
    category: "villas",
    era: "legacy",
    location: { en: "Al Khawaneej 2, Dubai", ar: "الخوانيج 2، دبي" },
    areaSqft: 7_888.69,
    consultant: "Al Anfal Engineering Consultants",
    images: [img("villa-al-khawaneej")],
  },
  {
    slug: "private-villas-dubai",
    title: { en: "Private Villas Across Dubai (20+)", ar: "فلل خاصة في أنحاء دبي (أكثر من 20)" },
    category: "villas",
    era: "legacy",
    location: {
      en: "Al Warqa, Al Barsha, Mirdif, Nad Al Hammar, Al Quoz, Jumeirah",
      ar: "الورقاء، البرشاء، مردف، ند الحمر، القوز، جميرا",
    },
    completed: true,
    images: [
      img("villa-05"),
      img("villa-03"),
      img("villa-01"),
      img("villa-02"),
      img("villa-04"),
      img("villa-06"),
      img("villa-07"),
      img("villa-08"),
      img("villa-09"),
      img("villa-10"),
      img("villa-11"),
    ],
    featured: true,
  },
  {
    slug: "global-village",
    title: { en: "Cultural Stage & Rest Rooms", ar: "المسرح الثقافي ودورات المياه" },
    category: "leisure",
    era: "legacy",
    location: { en: "Global Village, Dubai", ar: "القرية العالمية، دبي" },
    client: "Global Village",
    completed: true,
    images: [img("global-village-stage"), img("global-village-restrooms"), img("global-village-interior")],
    featured: true,
  },
  {
    slug: "al-nakhali-poultry",
    title: {
      en: "12 Poultry Farm Sheds with Machinery & Prefab Equipment",
      ar: "12 حظيرة دواجن مع توريد وتركيب الآلات والمعدات الجاهزة",
    },
    category: "poultry",
    era: "legacy",
    location: { en: "Al Nakhali Palace, Dubai", ar: "قصر النخالي، دبي" },
    client: "H.H. The Ruler's Court",
    completed: true,
    images: [img("poultry-al-nakhali"), img("poultry-al-nakhali-2")],
    featured: true,
  },
];

export const featuredProjects = projects.filter((p) => p.featured && p.images.length > 0);
